// apps/react/src/app/components/layout/DefaultPage.tsx
import { Fragment, ReactNode } from "react";
import { Link } from "react-router-dom";

export class BreadcrumbItem {
    text: string;
    routerLink?: string;

    constructor(text: string, routerLink?: string) {
        this.text = text;
        this.routerLink = routerLink;
    }

    isLink(): boolean {
        return !!this.routerLink;
    }
}

interface Props {
    title: string;
    breadcrumbs: BreadcrumbItem[];
    children: ReactNode;
}

const DefaultPage = ({ title, breadcrumbs, children }: Props) => {
    return (
        <>
            <div className="toolbar py-5 py-lg-15" id="kt_toolbar">
                <div id="kt_toolbar_container" className="container-xl d-flex flex-stack flex-wrap">
                    <div className="page-title d-flex flex-column">
                        <h1 className="d-flex text-white fw-bold fs-2qx my-1 me-5">
                            {title}
                        </h1>
                        <ul className="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-1">
                            <li className="breadcrumb-item text-white opacity-75">
                                <Link to="/" className="text-white text-hover-primary">
                                    <i className="ki-duotone ki-home fs-3 text-gray-400 me-n1"></i>
                                </Link>
                            </li>
                            { 
                                breadcrumbs && breadcrumbs.length > 0 && 
                                <li className="breadcrumb-item">
                                    <i className="ki-duotone ki-right fs-4 text-gray-700 mx-n1"></i>
                                </li> 
                            }
                            {
                                breadcrumbs.map((item, index) => (
                                    <Fragment key={'breadcrum-item' + index}>
                                        <li className="breadcrumb-item text-gray-700 fw-bold lh-1">
                                            {
                                                item.isLink() &&
                                                <a
                                                    className="text-muted cursor-pointer"
                                                >
                                                    {item.text}
                                                </a>
                                            }
                                            {
                                                item.isLink() ||
                                                <span>{item.text}</span>
                                            }
                                        </li>
                                        {
                                            index !== breadcrumbs.length - 1 &&
                                            <li className="breadcrumb-item">
                                                <i className="ki-duotone ki-right fs-4 text-gray-700 mx-n1"></i>
                                            </li>
                                        }
                                    </Fragment>
                                ))
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div id="kt_content_container" className="d-flex flex-column-fluid align-items-start container-xl">
                <div className="content flex-row-fluid" id="kt_content">
                    {children}
                </div>
            </div>
        </>
    )
}

export default DefaultPage

// apps/angular/src/app/layout/default-page.component.ts
import { Component, Injector, Input } from "@angular/core";
import { NavigationExtras, Router } from "@angular/router";
import { appModuleAnimation } from "@shared/animations/router-transition";
import { AppComponentBase } from "@shared/app-component-base";

export class BreadcrumbItem {
    text: string;
    routerLink?: string;
    navigationExtras?: NavigationExtras;

    constructor(text: string, routerLink?: string, navigationExtras?: NavigationExtras) {
        this.text = text;
        this.routerLink = routerLink;
        this.navigationExtras = navigationExtras;
    }

    isLink(): boolean {
        return !!this.routerLink;
    }
}

@Component({
    selector: 'default-page',
    templateUrl: './default-page.component.html',
    animations: [appModuleAnimation()]
})
export class DefaultPageComponent extends AppComponentBase {
    @Input() title: string;
    @Input() breadcrumbs: BreadcrumbItem[];

    constructor(private _router: Router, injector: Injector) {
        super(injector);
    }

    goToBreadcrumb(breadcrumb: BreadcrumbItem): void {
        if (!breadcrumb.routerLink) {
            return;
        }

        if (breadcrumb.navigationExtras) {
            this._router.navigate([breadcrumb.routerLink], breadcrumb.navigationExtras);
        } else {
            this._router.navigate([breadcrumb.routerLink]);
        }
    }
}

<div [@routerTransition]>
    <div id="kt_app_toolbar" class="app-toolbar pt-8">
        <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex align-items-stretch">
            <div class="app-toolbar-wrapper d-flex flex-stack flex-wrap gap-4 w-100">
                <div class="page-title d-flex flex-column gap-1 me-3 mb-2">
                    <ul class="breadcrumb breadcrumb-separatorless fw-semibold mb-6">
                        <li class="breadcrumb-item text-gray-700 fw-bold lh-1">
                            <a href="/" class="text-gray-500">
                                <i class="ki-duotone ki-home fs-3 text-gray-400 me-n1"></i>
                            </a>
                        </li>
                        <li *ngIf="breadcrumbs && breadcrumbs.length > 0" class="breadcrumb-item">
                            <i class="ki-duotone ki-right fs-4 text-gray-700 mx-n1"></i>
                        </li>
                        <ng-container *ngFor="let item of breadcrumbs; let isLast = last">
                            <li class="breadcrumb-item text-gray-700 fw-bold lh-1">
                                <a
                                    *ngIf="item.isLink()"
                                    style="cursor: pointer"
                                    (click)="goToBreadcrumb(item)"
                                    class="text-muted"
                                >
                                    {{ item.text }}
                                </a>
                                <span *ngIf="!item.isLink()">{{ item.text }}</span>
                            </li>
                            <li *ngIf="!isLast" class="breadcrumb-item">
                                <i class="ki-duotone ki-right fs-4 text-gray-700 mx-n1"></i>
                            </li>
                        </ng-container>
                    </ul>
                    <h1 class="page-heading d-flex flex-column justify-content-center text-dark fw-bolder fs-1 lh-0">{{ title }}</h1>
                </div>
                <ng-content select="div[role=action-button]"></ng-content>
            </div>
        </div>
    </div>
    <div id="kt_app_content" class="app-content d-flex flex-column flex-root flex-column-fluid">
        <div id="kt_app_content_container" class="app-container container-fluid d-flex flex-column flex-root">
            <ng-content select="div[role=app-content]"></ng-content>
        </div>
    </div>
</div>
